### ISSUE TITLE
CDC Stressor Tool failing during a longevity-10g-3h-test

### ISSUE THREAD

**Issue by fgelcer** [piodul/cdc-stressor#3]
during `longevity-10g-3h-test` we had a nemesis called `RunCDCStressorTool` and it failed.
the command executed by nemesis is `cdc-stressor -stream-query-round-duration 30s`
the error message is:
```
TransportError(429, 'circuit_breaking_exception', '[parent] Data too
 large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [reques
t=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')
```
the logs to the failed are here:
[sct.log](https://cloudius-jenkins-test.s3.amazonaws.com/49981de7-9e01-45d3-8d59-9b3f07ce9d34/20210620_200301/sct-runner-49981de7.zip)
[db-cluster.logs](https://cloudius-jenkins-test.s3.amazonaws.com/49981de7-9e01-45d3-8d59-9b3f07ce9d34/20210620_200301/db-cluster-49981de7.zip)

**Comment by fgelcer** [comment]
@piodul , FYI

**Comment by piodul** [comment]
I don't think this is a problem with cdc-stressor:

	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-06-20 18:58:38.967: (ThreadFailedEvent Severity.ERROR) period_type=not-set event_id=09f8434b-8696-47a7-8ab9-dad05141899f: message=TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 272, in run
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.disrupt()
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2999, in wrapper
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     args[0].update_stats(disrupt, status, log_info)
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 192, in update_stats
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.es_publisher.publish(disrupt_name=disrupt, status=status, data=data)
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis_publisher.py", line 90, in publish
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     res = self.es.index(index=self.index_name, doc_type='nemesis', body=new_nemesis_data)
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, params=params, headers=headers, **kwargs)
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 398, in index
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return self.transport.perform_request(
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 415, in perform_request
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     raise e
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     status, headers_response, data = connection.perform_request(
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self._raise_error(response.status, raw_data)
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
	< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')

It looks like SCT failed to push some data to elasticsearch. [TransportError](https://elasticsearch-py.readthedocs.io/en/7.10.0/exceptions.html#elasticsearch.TransportError) 429 suggests a [HTTP 429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) response - perhaps elasticsearch was overloaded?

**Comment by fgelcer** [comment]
> I don't think this is a problem with cdc-stressor:
> 
> ```
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-06-20 18:58:38.967: (ThreadFailedEvent Severity.ERROR) period_type=not-set event_id=09f8434b-8696-47a7-8ab9-dad05141899f: message=TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 272, in run
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.disrupt()
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2999, in wrapper
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     args[0].update_stats(disrupt, status, log_info)
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 192, in update_stats
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.es_publisher.publish(disrupt_name=disrupt, status=status, data=data)
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis_publisher.py", line 90, in publish
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     res = self.es.index(index=self.index_name, doc_type='nemesis', body=new_nemesis_data)
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, params=params, headers=headers, **kwargs)
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 398, in index
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return self.transport.perform_request(
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 415, in perform_request
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     raise e
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     status, headers_response, data = connection.perform_request(
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self._raise_error(response.status, raw_data)
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
> < t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')
> ```
> 
> It looks like SCT failed to push some data to elasticsearch. [TransportError](https://elasticsearch-py.readthedocs.io/en/7.10.0/exceptions.html#elasticsearch.TransportError) 429 suggests a [HTTP 429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) response - perhaps elasticsearch was overloaded?

yes, SCT could have multiple failures, but the one i posted above happened in different times, for different reasons, and they are not related, but yes, it also has this elasticsearch failure (but not only it)

**Comment by piodul** [comment]
More info from sct.log:

	< t:2021-06-20 18:56:36,577 f:nemesis.py      l:1124 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method run_cdcstressor_tool
	< t:2021-06-20 18:56:36,578 f:nemesis.py      l:635  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> RunCDCStressorTool
	< t:2021-06-20 18:56:36,578 f:nemesis.py      l:637  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: RunCDCStressorTool

	...

	< t:2021-06-20 18:56:37,205 f:nemesis.py      l:2868 c:sdcm.nemesis         p:WARNING > sdcm.nemesis.SisyphusMonkey: CDC is not enabled on any table. Skipping
	< t:2021-06-20 18:56:37,206 f:nemesis.py      l:1134 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: <<<<<<<<<<<<<Finished random_disrupt_method run_cdcstressor_tool

	...

	< t:2021-06-20 18:56:37,207 f:nemesis.py      l:2992 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: RunCDCStressorTool duration -> 0 s
	< t:2021-06-20 18:56:37,207 f:nemesis.py      l:188  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Update nemesis info with: {'start': 1624215396, 'end': 1624215397, 'duration': 0, 'node': 'Node longevity-10gb-3h-master-db-node-49981de7-7 [13.48.177.46 | 10.0.1.183] (seed: False)', 'subtype': 'end'}

	...

	< t:2021-06-20 18:56:38,965 f:base.py         l:302  c:elasticsearch        p:DEBUG > > {"test_id":"49981de7-9e01-45d3-8d59-9b3f07ce9d34","job_name":"scylla-master/longevity/longevity-10gb-3h-test","test_name":"longevity_test.LongevityTest.test_custom_time","scylla_version":"4.6.dev","scylla_git_sha":"055bc33f0","nemesis_name":"RunCDCStressorTool","nemesis_duration":0,"start_time":"2021-06-20T18:56:36","end_time":"2021-06-20T18:56:37","target_node":"Node longevity-
	10gb-3h-master-db-node-49981de7-7 [13.48.177.46 | 10.0.1.183] (seed: False)","outcome":"passed"}
	< t:2021-06-20 18:56:38,965 f:base.py         l:307  c:elasticsearch        p:DEBUG > < {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]","bytes_wanted":1067233530,"bytes_limit":1020054732,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]","bytes_wanted":1067233530,"bytes_limit":1020054732,"durability":"TRANSIENT"},"status":429}

The `CDC is not enabled on any table. Skipping` line suggests that the cdc-stressor wasn't even run. After that, I believe that SCT tried to push the result of the nemesis to elasticsearch, but failed and an exception was thrown - because of that, SCT thought that the nemesis has failed.

I couldn't see any more runs of the `RunCDCStressorTool` nemesis in the log, so it seems that cdc-stressor wasn't run at all during the test. Therefore the failure couldn't have been caused by cdc-stressor.

**Comment by fgelcer** [comment]
> The `CDC is not enabled on any table. Skipping` line suggests that the cdc-stressor wasn't even run. After that, I believe that SCT tried to push the result of the nemesis to elasticsearch, but failed and an exception was thrown - because of that, SCT thought that the nemesis has failed.

true that the nemesis was skipped, but what does this "`circuit_breaking_exception`" is coming from? specially if the tool didn't run at all...

**Comment by dkropachev** [comment]
Hello Fabio, 

it is sct issue, AFAIK Valeriy is already working on fixing it.
Let's close the guy.

Thanks.

**Comment by fgelcer** [comment]
> Hello Fabio,
> 
> it is sct issue, AFAIK Valeriy is already working on fixing it.
> Let's close the guy.
> 
> Thanks.

closing

**Comment by fgelcer** [comment]
for reference:
https://github.com/scylladb/scylla-cluster-tests/issues/3728
